### ISSUE TITLE
CSSがうまくあたってないかもしれない

### ISSUE THREAD

**Issue by tetsuyas1** [tetsuyas1/sales_org_survey#22]

**Comment by kkanazaw** [comment]
今(2/28 10:00ごろ)PCで確認したところ、明らかに崩れている箇所はなさそうでした。
こちらどのページのどのあたりが崩れていたでしょうか？

考えられる原因
1. (CI設置中) コミット後にファイルが更新されるまでラグがあることがありました。今回もそれが起きていた可能性がある
2. ブラウザのキャッシュが効いていた可能性
3. 崩れているの基準が異なっている。

**Comment by tetsuyas1** [comment]
OKです。多分1の問題ですね。

**Comment by kkanazaw** [comment]
了解しましたー。再発したらもう一度調べます
