### ISSUE TITLE
本番へのデプロイ環境を作る

### ISSUE THREAD

**Issue by tetsuyas1** [tetsuyas1/sales_org_survey#26]
本番は、services.and-d.co.jp を想定
既存のプロバイダーのレンタルサーバなので、多分自動化とかはできない。
手作業で上げていく感じでOK
アクセス情報は共有します。

**Comment by tetsuyas1** [comment]
これ金澤さんにアサインしたいです

**Comment by kkanazaw** [comment]
# 受け入れ条件
- services.and-d.co.jpのレンサバは秋口に捨てる予定
- ドメインが https://tetsuyas1.github.io/tetsuyas1/sales_org_survey/ でなければいい。
- heroku等で独自ドメインが当てられればいい

**Comment by kkanazaw** [comment]
複数サイト設定できるようになってました。

- sales-org-survey:  https://sales-org-survey.and-d.co.jp/
- サイトURL(旧会社ブログ):  https://blog.designrule.jp/

# 設定方法

1. route53で CNAMEを設定。向き先をどちらもtetsuyas1.github.ioにする。
```
sales-org-survey.and-d.co.jp. | CNAME | tetsuyas1.github.io
blog.designrule.jp. | CNAME | tetsuyas1.github.io
```

2. それぞれのリポジトリの設定画面で、CustomDomainを設定する
ドメイン名にアンスコは使えないので、ハイフンに変換

```
github リポジトリ https://github.com/tetsuyas1/sales_org_survey/settings
Custom domain sales-org-survey.and-d.co.jp

github リポジトリ https://github.com/tetsuyas1/tetsuyas1.github.io/settings
Custom domain blog.designrule.jp
```

# 参考
- 以前は、1つのリポジトリのCustom domainを変更すると、全部のリポジトリの設定が切り替わってしまっていましたが、今は直っているようです。
- 参考にした資料だと *.github.ioという名前のリポジトリを作ってしまうとうまく動かないようでしたが、これも今は直っているようでした。

- [GitHub Pagesで複数の独自ドメインのHTTPS(TLS,SSL)サイトを運用する - このすみろぐ](https://www.konosumi.net/entry/2018/07/01/190200)
- [複数のGitHubページとDNSによるカスタムドメイン - コードログ](https://codeday.me/jp/qa/20181212/55476.html)
