### ISSUE TITLE
最終ページのお問い合わせ目立たせる

### ISSUE THREAD

**Issue by tetsuyas1** [tetsuyas1/sales_org_survey#28]
その他）
上記修正の際にデモ画面の最終ページに問合せボタンを付けて「お問い合わせ」のページに接続していただければと思います。
→「お問い合わせ」が白抜きで小さく目立たないので、目立つようにする。
　　※下部の「お問い合わせ」とは別に「問合せボタン」を付けるのでも良いです。

**Comment by kkanazaw** [comment]
政策秘書に依頼しました
https://cyclo-creativecloud.com/projects/21064
