### ISSUE TITLE
石田さんの希望

### ISSUE THREAD

**Issue by tetsuyas1** [tetsuyas1/sales_org_survey#38]
[![Screenshot from Gyazo](https://gyazo.com/4a8a1735a2fa01abe958a85a556cfad5/raw)](https://gyazo.com/4a8a1735a2fa01abe958a85a556cfad5)

**Comment by tetsuyas1** [comment]
[![Screenshot from Gyazo](https://gyazo.com/0599687b5177b0a7d6ac3addff1e3ed2/raw)](https://gyazo.com/0599687b5177b0a7d6ac3addff1e3ed2)

**Comment by tetsuyas1** [comment]
@haruka-sato こちらご確認ください

**Comment by haruka-sato** [comment]
@tetsuyas1 ご連絡いただきありがとうございます。
ただいま確認いたしますので少々お待ち下さい。
どうぞよろしくお願いいたします。

**Comment by haruka-sato** [comment]
@tetsuyas1 

https://sales-org-survey.and-d.co.jp/

こちらのサイトを確認したところ、CSSが更新されていないようです。
お手数ですがご確認いただけますと幸いです。

どうぞよろしくお願いいたします。
